name: Publish Lib CRM CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: "14.x"
    - run: npm install
    - run: npm run build:crm
    - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
    - name: Publish Ng package on NPM 📦
      run: npm publish --access public
      working-directory: dist/orion-crm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
